
GET  https://music.huzhihui.org.cn/login/cellphone?phone=13683656716&password=Netease123.

###

GET  https://music.huzhihui.org.cn/banner

###

GET  https://music.huzhihui.org.cn/album/newest

###
GET  https://music.huzhihui.org.cn/personalized/newsong

###
GET  https://music.huzhihui.org.cn/personalized/mv

###
GET  https://music.huzhihui.org.cn/program/recommend

###
GET  https://music.huzhihui.org.cn/song/url?id=1371353582

###

